query RetrieveJobs {
  getJobs {
    ...JobData
  }
}

mutation CreateJob ($inputs: JobInputType!) {
  createJob (inputs: $inputs) {
    job {
      ...JobData
    }
  }
}

mutation UpdateJob ($inputs: JobInputType!) {
  updateJob (inputs: $inputs) {
    job {
      ...JobData
    }
  }
}

mutation DeleteJob ($inputs: JobInputType!) {
  deleteJob (inputs: $inputs) {
    job {
      ...JobData
    }
  }
}

mutation ToggleSaveJob ($keycloakUserId: String!, $jobId: String!, $isSave: Boolean!) {
  toggleSaveJob (
    keycloakUserId: $keycloakUserId
    jobId: $jobId
    isSave: $isSave
  ) {
    job {
      ...JobData
    }
  }
}

fragment JobData on JobType {
  id
  poster {
    keycloakUserId
  }
  title
  employer
  location
  salary
  description
  savedBy {
    keycloakUserId
  }
  applications {
    applicant {
      keycloakUserId
    }
    dateGraduated
    dateStart
    reason
  }
}