query RetrieveJobs($keycloakUserId: String!) {
  getJobs {
    ...JobData
  }
}

mutation CreateJob($keycloakUserId: String!, $inputs: JobInputType!) {
  createJob(inputs: $inputs) {
    job {
      ...JobData
    }
  }
}

mutation UpdateJob($keycloakUserId: String!, $inputs: JobInputType!) {
  updateJob(inputs: $inputs) {
    job {
      ...JobData
    }
  }
}

mutation DeleteJob($keycloakUserId: String!, $inputs: JobInputType!) {
  deleteJob(inputs: $inputs) {
    job {
      ...JobData
    }
  }
}

fragment JobData on JobType {
  id
  postedOn
  poster
  title
  employer
  location
  salary
  description
  # applications {
  #   appliedOn
  #   applicant
  #   dateGraduated
  #   dateStart
  #   reason
  # }
  metadata(keycloakUserId: $keycloakUserId) {
    userIsPoster
    userIsApplicant
    userHasSaved
  }
}
