query SearchUsers($keycloakUserId: String!, $keyword: String!) {
  searchUsers(search: $keyword) {
    keycloakUserId
    profile {
      fullName
      university
      major
    }
    metadata(keycloakUserId: $keycloakUserId) {
      userIsConfirmedFriend
      userIsPendingFriend
      userSentFriendsRequest
    }
  }
}

mutation CreateRetrieveUser($keycloakUserId: String!) {
  createRetrieveUser(inputs: { keycloakUserId: $keycloakUserId }) {
    user {
      ...UserData
    }
  }
}

mutation UpdateUserProfile(
  $keycloakUserId: String!
  $profile: UserProfileInputType!
) {
  updateUser(inputs: { keycloakUserId: $keycloakUserId, profile: $profile }) {
    user {
      ...UserData
    }
  }
}

mutation UpdateUserSettings(
  $keycloakUserId: String!
  $settings: UserSettingsInputType!
) {
  updateUser(inputs: { keycloakUserId: $keycloakUserId, settings: $settings }) {
    user {
      ...UserData
    }
  }
}

mutation UpdateUserSaveJob($keycloakUserId: String!, $saveJob: String!) {
  updateUser(inputs: { keycloakUserId: $keycloakUserId, saveJob: $saveJob }) {
    user {
      ...UserData
    }
  }
}

mutation UpdateUserUnsaveJob($keycloakUserId: String!, $unsaveJob: String) {
  updateUser(
    inputs: { keycloakUserId: $keycloakUserId, unsaveJob: $unsaveJob }
  ) {
    user {
      ...UserData
    }
  }
}

fragment UserData on UserType {
  keycloakUserId
  isPlusUser
  profile {
    fullName
    university
    major
    about
    employment {
      id
      title
      employer
      dateStarted
      dateEnded
      location
      description
    }
    education {
      id
      degree
      school
      dateStarted
      dateEnded
      location
      description
    }
  }
  settings {
    subscriptionEmail
    subscriptionSms
    targetedAdvertising
    language
  }
  friends
  jobsSaved
}
